In [26]:
import pandas as pd
import numpy as np

In [19]:
#df = pd.read_json('/Users/hadoop/Python Notebook/Data/yelp_training_set/yelp_training_set_business.json',lines=True)

In [46]:
#df = pd.read_csv('/Users/hadoop/Python Notebook/Data/yelp.csv')
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/yelp.csv')

In [47]:
df.columns

Index(['business_id', 'date', 'review_id', 'stars', 'text', 'type', 'user_id',
       'cool', 'useful', 'funny'],
      dtype='object')

In [48]:
df.shape

(10000, 10)

In [67]:
df51 = df[(df['stars']==5) | (df['stars']==1)]

In [90]:
#X = df51['text']
#y= df51['stars']
X = df['text']
y= df['stars']

In [91]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [112]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=2)
vect = CountVectorizer()
#dtm=vect.fit_transform(X_train)
dtm=vect.fit_transform(X_train)
dtm

<7500x25639 sparse matrix of type '<class 'numpy.int64'>'
	with 621549 stored elements in Compressed Sparse Row format>

In [93]:
from sklearn.naive_bayes import MultinomialNB

In [94]:
mnb = MultinomialNB()
mnb.fit(dtm,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [113]:
dtt= vect.transform(X_test)
dtt

<2500x25639 sparse matrix of type '<class 'numpy.int64'>'
	with 201660 stored elements in Compressed Sparse Row format>

In [97]:
y_pred_class = mnb.predict(dtt)

In [98]:
y_pred_class

array([5, 4, 5, ..., 4, 4, 1])

In [117]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred_class)

0.48520000000000002

In [118]:
metrics.confusion_matrix(y_test,y_pred_class)

array([[ 57,  29,  19,  71,  24],
       [ 13,  20,  30, 140,  27],
       [  2,   7,  33, 276,  31],
       [  4,   1,  18, 655, 211],
       [  1,   0,   2, 381, 448]])

In [121]:
#calculate the actual class distribution of test
y_test.value_counts()

4    889
5    832
3    349
2    230
1    200
Name: stars, dtype: int64

In [147]:
# calculate the null accuracy of each star rating
nullaccuracy_4 = y_test.value_counts().loc[4]/y_test.shape

nullaccuracy_5 = y_test.value_counts().loc[5]/y_test.shape

nullaccuracy_3 = y_test.value_counts().loc[3]/y_test.shape

nullaccuracy_2 = y_test.value_counts().loc[2]/y_test.shape

nullaccuracy_1 = y_test.value_counts().loc[1]/y_test.shape



In [155]:
[nullaccuracy_4[0],nullaccuracy_5[0],nullaccuracy_3[0],nullaccuracy_2[0],nullaccuracy_1[0]]

[0.35560000000000003,
 0.33279999999999998,
 0.1396,
 0.091999999999999998,
 0.080000000000000002]

In [157]:
mnb.feature_count_.shape

(5, 25639)

In [158]:
mnb.feature_count_[0, :]

array([ 28.,   2.,   3., ...,   0.,   0.,   0.])